
import { NextResponse } from 'next/server';

const doctors = [
  {
    name: "Michael Smith",
    specialty: "MBBS - Gynecology and Pediatric Medicine",
    image: "https://placehold.co/250x250.png",
    hint: "male doctor",
    verified: true,
    rating: 4.8,
    reviews: 120,
    location: "New York, USA",
    availability: "Available Mon, 24 Dec",
    price: "₦150 - ₦300",
  },
  {
    name: "Tom Hanky",
    specialty: "BDS, MDS - Oral & Maxillofacial Surgery",
    image: "https://placehold.co/250x250.png",
    hint: "doctor portrait",
    verified: true,
    rating: 4.9,
    reviews: 215,
    location: "Los Angeles, USA",
    availability: "Available Tue, 25 Dec",
    price: "₦200 - ₦400",
  },
  {
    name: "Leke Alder",
    specialty: "MDS - Periodontology and Oral implantology, BDS",
    image: "https://placehold.co/250x250.png",
    hint: "female doctor",
    verified: true,
    rating: 4.7,
    reviews: 89,
    location: "Chicago, USA",
    availability: "Available Wed, 26 Dec",
    price: "₦180 - ₦350",
  },
  {
    name: "Chisom Agu",
    specialty: "MDS - Periodontology and Oral implantology, BDS",
    image: "https://placehold.co/250x250.png",
    hint: "female doctor glasses",
    verified: true,
    rating: 5.0,
    reviews: 302,
    location: "Houston, USA",
    availability: "Available Thu, 27 Dec",
    price: "₦250 - ₦500",
  },
  {
    name: "Precious Brownson",
    specialty: "MDS - Periodontology and Oral implantology, BDS",
    image: "https://placehold.co/250x250.png",
    hint: "female doctor looking",
    verified: true,
    rating: 4.8,
    reviews: 150,
    location: "Phoenix, USA",
    availability: "Available Fri, 28 Dec",
    price: "Free",
  },
  {
    name: "Gideon Anthony",
    specialty: "MBBS - Neurosurgeon and Brain Expert",
    image: "https://placehold.co/250x250.png",
    hint: "doctor smiling",
    verified: true,
    rating: 4.9,
    reviews: 180,
    location: "Philadelphia, USA",
    availability: "Available Sat, 29 Dec",
    price: "₦300 - ₦600",
  },
  {
    name: "Glory Felix",
    specialty: "BDS, MDS - Optometrist, and Eye Surgeon",
    image: "https://placehold.co/250x250.png",
    hint: "woman smiling",
    verified: true,
    rating: 4.6,
    reviews: 95,
    location: "San Antonio, USA",
    availability: "Available Sun, 30 Dec",
    price: "₦120 - ₦250",
  },
  {
    name: "Ferdinand Lucios",
    specialty: "MDS - Obsteriology, Oncology, and Dietetics BDS",
    image: "https://placehold.co/250x250.png",
    hint: "male doctor portrait",
    verified: true,
    rating: 4.7,
    reviews: 210,
    location: "San Diego, USA",
    availability: "Available Mon, 31 Dec",
    price: "₦220 - ₦450",
  },
];

export async function GET() {
  return NextResponse.json(doctors);
}
