/**
 * This code was generated by Builder.io.
 */
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { Button } from "@/components/ui/button";
import {
  Table,
  TableHeader,
  TableRow,
  TableHead,
  TableBody,
  TableCell,
} from "@/components/ui/table";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";

const patientData = [
  {
    name: "Susan Mandi",
    apptDate: "14 Nov 2023",
    purpose: "Consult",
    type: "New Patient",
    paidAmount: "$100",
  },
  {
    name: "Brandon M",
    apptDate: "11 Nov 2023",
    purpose: "Consult",
    type: "Old Patient",
    paidAmount: "$150",
  },
  {
    name: "Sals K Y",
    apptDate: "20 Oct 2023",
    purpose: "Consult",
    type: "New Patient",
    paidAmount: "$200",
  },
  {
    name: "Chioma Okoro",
    apptDate: "22 Oct 2023",
    purpose: "New Test",
    type: "Old Patient",
    paidAmount: "$250",
  },
  {
    name: "Aliyu M.",
    apptDate: "25 Oct 2023",
    purpose: "Check up",
    type: "New Patient",
    paidAmount: "$120",
  },
];

export default function Dashboard() {
  return (
    <div className="space-y-6">
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        <Card>
          <CardHeader className="flex flex-row items-center justify-between pb-2">
            <CardTitle className="text-sm font-medium">Total Patient</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">1500</div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between pb-2">
            <CardTitle className="text-sm font-medium">Today Patient</CardTitle>
            <span className="text-xs text-muted-foreground">15 Nov, 2023</span>
          </CardHeader>
          <CardContent className="flex items-center gap-4">
            <div className="text-2xl font-bold">165</div>
            <Progress value={82.5} className="h-2" />
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between pb-2">
            <CardTitle className="text-sm font-medium">Appointment</CardTitle>
            <span className="text-xs text-muted-foreground">15 Nov, 2023</span>
          </CardHeader>
          <CardContent className="flex items-center gap-4">
            <div className="text-2xl font-bold">85</div>
            <Progress value={42.5} className="h-2" />
          </CardContent>
        </Card>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <Card>
          <CardContent className="p-4">
            <div className="flex items-center gap-4">
                <div className="bg-blue-100 p-3 rounded-full">
                    <svg className="w-6 h-6 text-blue-500" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 10v-1m0-6h.01M6 12H5m14 0h-1m-1-5l-.707-.707M6.707 6.707L6 6m12 12l-.707-.707M6.707 17.293L6 18"></path></svg>
                </div>
              <div>
                <p className="text-sm text-muted-foreground">Total Income</p>
                <p className="text-xl font-bold">$50,000.00</p>
              </div>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-4">
            <div className="flex items-center gap-4">
                <div className="bg-pink-100 p-3 rounded-full">
                    <svg className="w-6 h-6 text-pink-500" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z"></path></svg>
                </div>
              <div>
                <p className="text-sm text-muted-foreground">Total Appointments</p>
                <p className="text-xl font-bold">50,028</p>
              </div>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-4">
            <div className="flex items-center gap-4">
                <div className="bg-green-100 p-3 rounded-full">
                    <svg className="w-6 h-6 text-green-500" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.653-.184-1.268-.5-1.82M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.653.184-1.268.5-1.82m5-10a3 3 0 11-6 0 3 3 0 016 0zm-3 3a3 3 0 100-6 3 3 0 000 6z"></path></svg>
                </div>
              <div>
                <p className="text-sm text-muted-foreground">Total Patients</p>
                <p className="text-xl font-bold">172,800</p>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      <Card>
        <CardHeader>
          <div className="flex justify-between items-center">
            <CardTitle>Patient Appointment</CardTitle>
            <div>
              <Button variant="outline" className="mr-2">Upcoming</Button>
              <Button>Today</Button>
            </div>
          </div>
        </CardHeader>
        <CardContent>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Patient Name</TableHead>
                <TableHead>Appt Date</TableHead>
                <TableHead>Purpose</TableHead>
                <TableHead>Type</TableHead>
                <TableHead>Paid Amount</TableHead>
                <TableHead></TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {patientData.map((patient, index) => (
                <TableRow key={index}>
                  <TableCell>
                    <div className="flex items-center gap-3">
                      <Avatar>
                        <AvatarImage src={`https://placehold.co/40x40.png?text=${patient.name.charAt(0)}`} alt={patient.name} />
                        <AvatarFallback>{patient.name.charAt(0)}</AvatarFallback>
                      </Avatar>
                      <span className="font-medium">{patient.name}</span>
                    </div>
                  </TableCell>
                  <TableCell>{patient.apptDate}</TableCell>
                  <TableCell>{patient.purpose}</TableCell>
                  <TableCell>
                    <span className={`px-2 py-1 rounded-full text-xs ${
                      patient.type === 'New Patient' ? 'bg-blue-100 text-blue-800' : 'bg-green-100 text-green-800'
                    }`}>{patient.type}</span>
                  </TableCell>
                  <TableCell>{patient.paidAmount}</TableCell>
                  <TableCell>
                    <Button variant="ghost" size="icon">
                      ...
                    </Button>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </CardContent>
      </Card>
    </div>
  );
}
