/**
 * This code was generated by Builder.io.
 */
"use client";

import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import Link from "next/link";
import {
  Brain,
  HeartPulse,
  Search,
  ChevronRight,
  CheckCircle2,
  Calendar,
  Clock,
  MapPin,
  ChevronLeft,
  Mail,
  Phone,
  Menu,
} from "lucide-react";
import { Sheet, SheetContent, SheetTrigger, SheetHeader, SheetTitle } from "@/components/ui/sheet";

const DentistIcon = (props: React.SVGProps<SVGSVGElement>) => (
  <svg
    {...props}
    xmlns="http://www.w3.org/2000/svg"
    width="48"
    height="48"
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth="1.5"
    strokeLinecap="round"
    strokeLinejoin="round"
  >
    <path d="M12.485 2.49a.5.5 0 0 0-.485.51v.002l-2.999 6c-.03.06-.06.12-.08.18L8.9 9.2a.5.5 0 0 0-.02.2v8.1a1.5 1.5 0 0 0 1.5 1.5h4.24a1.5 1.5 0 0 0 1.5-1.5V9.4a.5.5 0 0 0-.02-.2l-.022-.04-2.999-6a.5.5 0 0 0-.485-.51Z" />
    <path d="M12.485 18v-4.5" />
    <path d="M12.485 2.5a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5Z" />
  </svg>
);

const UrologyIcon = (props: React.SVGProps<SVGSVGElement>) => (
  <svg
    {...props}
    xmlns="http://www.w3.org/2000/svg"
    width="48"
    height="48"
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth="1.5"
    strokeLinecap="round"
    strokeLinejoin="round"
  >
    <path d="M10.22 6.31C9.44 5.53 8.32 5 7 5c-2.76 0-5 2.24-5 5s2.24 5 5 5c1.32 0 2.44-.53 3.22-1.31" />
    <path d="M13.78 6.31C14.56 5.53 15.68 5 17 5c2.76 0 5 2.24 5 5s-2.24 5-5 5c-1.32 0-2.44-.53-3.22-1.31" />
    <path d="M15.5 12.5c0 2.48-1.57 4.5-3.5 4.5s-3.5-2.02-3.5-4.5" />
  </svg>
);

const CardiologyIcon = (props: React.SVGProps<SVGSVGElement>) => (
  <svg
    {...props}
    width="48"
    height="48"
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth="1.5"
    strokeLinecap="round"
    strokeLinejoin="round"
  >
    <path d="M12 20.84l-1.41-1.41C5.63 14.47 2 11.25 2 7.5 2 4.42 4.42 2 7.5 2c1.74 0 3.41.81 4.5 2.09C13.09 2.81 14.76 2 16.5 2 19.58 2 22 4.42 22 7.5c0 3.75-3.63 6.97-8.59 11.93L12 20.84z" />
  </svg>
);

const OrthopedicsIcon = (props: React.SVGProps<SVGSVGElement>) => (
    <svg 
    {...props}
    width="48"
    height="48"
    viewBox="0 0 24 24" 
    fill="none" 
    stroke="currentColor" 
    strokeWidth="1.5" 
    strokeLinecap="round" 
    strokeLinejoin="round">
        <path d="M10 6.605a1 1 0 0 1 1.638-.77l4 5a1 1 0 0 1 0 1.54l-4 5A1 1 0 0 1 10 16.605V6.605z" />
        <path d="M6 7h1" />
        <path d="M6 12h1" />
        <path d="M6 17h1" />
    </svg>
);

const NovainLogo = (props: React.SVGProps<SVGSVGElement>) => (
  <svg {...props} width="124" height="34" viewBox="0 0 124 34" fill="none" xmlns="http://www.w3.org/2000/svg">
    <path d="M25.8079 9.30872V1.02734H33.0116V22.613H25.8079V14.1201C25.8079 13.091 25.8079 12.062 25.8079 10.9907C25.7656 10.1508 25.5562 9.56208 24.8827 9.17721C24.2092 8.79234 23.3241 8.79234 22.4812 9.135L17.6713 10.8142V2.8858L25.8079 9.30872Z" fill="#002244"/>
    <path d="M0.852051 1.02734H8.05574V22.613H0.852051V1.02734Z" fill="#002244"/>
    <path d="M17.0689 22.613V14.9961L9.65361 17.792V22.613H17.0689Z" fill="#002244"/>
    <path d="M17.0689 1.02734H9.65361V13.6264L17.0689 11.2371V1.02734Z" fill="#002244"/>
    <path d="M51.841 11.8949C51.841 12.9239 51.1528 13.5915 50.1534 13.5915C49.154 13.5915 48.4658 12.9239 48.4658 11.8949C48.4658 10.8658 49.154 10.1982 50.1534 10.1982C51.1528 10.1982 51.841 10.8658 51.841 11.8949ZM50.1534 22.8245C45.3435 22.8245 41.5173 18.7844 41.5173 11.8949C41.5173 4.96299 45.3435 1.02734 50.1534 1.02734C54.9633 1.02734 58.7472 4.96299 58.7472 11.8949C58.7472 18.7844 54.9633 22.8245 50.1534 22.8245Z" fill="#002244"/>
    <path d="M78.6942 9.30872V1.02734H85.8979V22.613H78.6942V14.1201C78.6942 13.091 78.6942 12.062 78.6942 10.9907C78.6519 10.1508 78.4425 9.56208 77.769 9.17721C77.0955 8.79234 76.2104 8.79234 75.3675 9.135L70.5576 10.8142V2.8858L78.6942 9.30872Z" fill="#002244"/>
    <path d="M63.7383 1.02734H70.942V22.613H63.7383V1.02734Z" fill="#002244"/>
    <path d="M93.3039 1.02734H100.508V22.613H93.3039V1.02734Z" fill="#002244"/>
    <path d="M101.455 1.02734H110.384L105.107 11.8949L110.173 22.613H101.58L98.636 16.3421H93.1345V22.613H85.9308V1.02734H98.4665C99.4659 1.02734 100.351 1.54188 100.815 2.43962C101.279 3.33736 101.279 4.40871 100.815 5.30645C100.351 6.20419 99.4659 6.71873 98.4665 6.71873H93.1345V10.1135H97.7497L101.455 1.02734Z" fill="#46C8F5"/>
    <path d="M40.2458 31.5208L34.1171 25.8624L40.2458 31.5208Z" fill="#46C8F5"/>
    <path d="M40.542 31.2417L34.1171 25.2842L40.542 31.2417Z" fill="#46C8F5"/>
    <path d="M34.1171 25.2842L40.5843 31.2839L34.1171 25.2842Z" fill="#46C8F5"/>
    <path d="M40.5843 31.2839L34.1171 25.2842L40.5843 31.2839Z" fill="#46C8F5"/>
    <path d="M34.1171 25.2842L40.542 31.2417L34.1171 25.2842Z" fill="#46C8F5"/>
    <path d="M40.542 31.2417L34.1171 25.2842L40.542 31.2417Z" fill="#46C8F5"/>
    <path d="M34.1171 25.2842L40.2458 31.5208L34.1171 25.2842Z" fill="#46C8F5"/>
    <path d="M40.2458 31.5208L34.1171 25.2842L40.2458 31.5208Z" fill="#46C8F5"/>
    <path d="M40.2035 25.0938H33.8208L40.2035 25.0938Z" fill="#46C8F5"/>
    <path d="M40.2035 25.0938H33.8208" stroke="#46C8F5" strokeWidth="1.5" strokeLinecap="round"/>
    <path d="M45.5426 25.0938H41.6885" stroke="#46C8F5" strokeWidth="1.5" strokeLinecap="round"/>
    <path d="M45.416 31.5208L40.2458 25.2842" stroke="#46C8F5" strokeWidth="1.5" strokeLinecap="round"/>
    <path d="M40.542 31.2417L34.1171 25.2842" stroke="#46C8F5" strokeWidth="1.5" strokeLinecap="round"/>
    <path d="M49.4912 31.5208H55.8739" stroke="#46C8F5" strokeWidth="1.5" strokeLinecap="round"/>
    <path d="M52.6826 31.5208V25.2419" stroke="#46C8F5" strokeWidth="1.5" strokeLinecap="round"/>
    <path d="M59.3204 31.5208H65.7031" stroke="#46C8F5" strokeWidth="1.5" strokeLinecap="round"/>
    <path d="M62.5118 31.5208V25.2419" stroke="#46C8F5" strokeWidth="1.5" strokeLinecap="round"/>
    <path d="M69.0494 28.3813C69.0494 26.5925 70.472 25.2419 72.1866 25.2419H73.0336C74.7482 25.2419 76.1708 26.5925 76.1708 28.3813V31.5208H69.0494V28.3813Z" stroke="#46C8F5" strokeWidth="1.5" strokeLinecap="round"/>
    <path d="M80.0197 25.2419H78.291V31.5208H80.0197V25.2419Z" stroke="#46C8F5" strokeWidth="1.5" strokeLinecap="round"/>
    <path d="M86.317 31.5208L81.1467 25.2842" stroke="#46C8F5" strokeWidth="1.5" strokeLinecap="round"/>
    <path d="M81.4258 31.2417L87.8507 25.2842" stroke="#46C8F5" strokeWidth="1.5" strokeLinecap="round"/>
    <path d="M90.3113 25.2419V31.5208" stroke="#46C8F5" strokeWidth="1.5" strokeLinecap="round"/>
    <path d="M90.3113 27.5029H93.3039" stroke="#46C8F5" strokeWidth="1.5" strokeLinecap="round"/>
    <path d="M95.6698 25.2419L99.6384 31.5208L103.607 25.2419" stroke="#46C8F5" strokeWidth="1.5" strokeLinecap="round"/>
    <path d="M123.148 11.8949C123.148 12.9239 122.46 13.5915 121.461 13.5915C120.461 13.5915 119.773 12.9239 119.773 11.8949C119.773 10.8658 120.461 10.1982 121.461 10.1982C122.46 10.1982 123.148 10.8658 123.148 11.8949ZM121.461 22.8245C116.651 22.8245 112.825 18.7844 112.825 11.8949C112.825 4.96299 116.651 1.02734 121.461 1.02734C126.271 1.02734 130.055 4.96299 130.055 11.8949C130.055 18.7844 126.271 22.8245 121.461 22.8245Z" fill="#002244"/>
    </svg>
);

const NovainLogoWhite = (props: React.SVGProps<SVGSVGElement>) => (
    <svg {...props} width="165" height="45" viewBox="0 0 165 45" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path d="M34.4105 12.4116V1.36963H44.0155V30.1506H34.4105V18.8268C34.4105 17.4547 34.4105 16.0826 34.4105 14.6657C34.3541 13.5344 34.0749 12.7494 33.1769 12.2351C32.2789 11.7208 31.1008 11.7208 30.0028 12.1795L23.5618 14.4189V3.8477L34.4105 12.4116Z" fill="white"/>
        <path d="M0.999878 1.36963H10.6049V30.1506H0.999878V1.36963Z" fill="white"/>
        <path d="M22.7585 30.1506V19.9948L12.7249 23.7226V30.1506H22.7585Z" fill="white"/>
        <path d="M22.7585 1.36963H12.7249V18.1685L22.7585 15.0094V1.36963Z" fill="white"/>
        <path d="M69.1213 15.8599C69.1213 17.232 68.214 18.1225 66.8711 18.1225C65.5281 18.1225 64.6208 17.232 64.6208 15.8599C64.6208 14.4878 65.5281 13.5973 66.8711 13.5973C68.214 13.5973 69.1213 14.4878 69.1213 15.8599ZM66.8711 30.4326C60.4301 30.4326 55.3559 25.0459 55.3559 15.8599C55.3559 6.62901 60.4301 1.36963 66.8711 1.36963C73.2828 1.36963 78.3278 6.62901 78.3278 15.8599C78.3278 25.0459 73.2828 30.4326 66.8711 30.4326Z" fill="white"/>
        <path d="M104.926 12.4116V1.36963H114.531V30.1506H104.926V18.8268C104.926 17.4547 104.926 16.0826 104.926 14.6657C104.88 13.5344 104.599 12.7494 103.701 12.2351C102.803 11.7208 101.625 11.7208 100.527 12.1795L94.0862 14.4189V3.8477L104.926 12.4116Z" fill="white"/>
        <path d="M84.9843 1.36963H94.5892V30.1506H84.9843V1.36963Z" fill="white"/>
        <path d="M124.405 1.36963H134.01V30.1506H124.405V1.36963Z" fill="white"/>
        <path d="M135.273 1.36963H147.178L140.143 15.8599L146.897 30.1506H135.44L131.514 21.7895H124.179V30.1506H114.574V1.36963H131.288C132.631 1.36963 133.809 2.05517 134.42 3.25281C135.03 4.45045 135.03 5.86734 134.42 7.06498C133.809 8.26262 132.631 8.95816 131.288 8.95816H124.179V13.4846H130.333L135.273 1.36963Z" fill="#A4DBF4"/>
        <path d="M53.6611 42.0277L45.4894 34.4831L53.6611 42.0277Z" fill="#A4DBF4"/>
        <path d="M54.056 41.6556L45.4894 33.7123L54.056 41.6556Z" fill="#A4DBF4"/>
        <path d="M45.4894 33.7123L54.1124 41.7118L45.4894 33.7123Z" fill="#A4DBF4"/>
        <path d="M54.1124 41.7118L45.4894 33.7123L54.1124 41.7118Z" fill="#A4DBF4"/>
        <path d="M45.4894 33.7123L54.056 41.6556L45.4894 33.7123Z" fill="#A4DBF4"/>
        <path d="M54.056 41.6556L45.4894 33.7123L54.056 41.6556Z" fill="#A4DBF4"/>
        <path d="M45.4894 33.7123L53.6611 42.0277L45.4894 33.7123Z" fill="#A4DBF4"/>
        <path d="M53.6611 42.0277L45.4894 33.7123L53.6611 42.0277Z" fill="#A4DBF4"/>
        <path d="M53.6047 33.458H45.0945L53.6047 33.458Z" fill="#A4DBF4"/>
        <path d="M53.6047 33.458H45.0945" stroke="#A4DBF4" strokeWidth="2" strokeLinecap="round"/>
        <path d="M60.7235 33.458H55.5847" stroke="#A4DBF4" strokeWidth="2" strokeLinecap="round"/>
        <path d="M60.5546 42.0277L53.6611 33.7123" stroke="#A4DBF4" strokeWidth="2" strokeLinecap="round"/>
        <path d="M54.056 41.6556L45.4894 33.7123" stroke="#A4DBF4" strokeWidth="2" strokeLinecap="round"/>
        <path d="M66.002 42.0277H74.5122" stroke="#A4DBF4" strokeWidth="2" strokeLinecap="round"/>
        <path d="M70.2571 42.0277V33.6558" stroke="#A4DBF4" strokeWidth="2" strokeLinecap="round"/>
        <path d="M79.0939 42.0277H87.6041" stroke="#A4DBF4" strokeWidth="2" strokeLinecap="round"/>
        <path d="M83.349 42.0277V33.6558" stroke="#A4DBF4" strokeWidth="2" strokeLinecap="round"/>
        <path d="M92.0659 37.8417C92.0659 35.4566 93.9625 33.6558 96.2492 33.6558H97.3781C99.6648 33.6558 101.561 35.4566 101.561 37.8417V42.0277H92.0659V37.8417Z" stroke="#A4DBF4" strokeWidth="2" strokeLinecap="round"/>
        <path d="M106.693 33.6558H104.385V42.0277H106.693V33.6558Z" stroke="#A4DBF4" strokeWidth="2" strokeLinecap="round"/>
        <path d="M115.09 42.0277L108.196 33.7123" stroke="#A4DBF4" strokeWidth="2" strokeLinecap="round"/>
        <path d="M108.568 41.6556L117.135 33.7123" stroke="#A4DBF4" strokeWidth="2" strokeLinecap="round"/>
        <path d="M120.415 33.6558V42.0277" stroke="#A4DBF4" strokeWidth="2" strokeLinecap="round"/>
        <path d="M120.415 36.6704H124.405" stroke="#A4DBF4" strokeWidth="2" strokeLinecap="round"/>
        <path d="M127.559 33.6558L132.851 42.0277L138.143 33.6558" stroke="#A4DBF4" strokeWidth="2" strokeLinecap="round"/>
        <path d="M164.197 15.8599C164.197 17.232 163.29 18.1225 161.947 18.1225C160.604 18.1225 159.697 17.232 159.697 15.8599C159.697 14.4878 160.604 13.5973 161.947 13.5973C163.29 13.5973 164.197 14.4878 164.197 15.8599ZM161.947 30.4326C155.506 30.4326 150.432 25.0459 150.432 15.8599C150.432 6.62901 155.506 1.36963 161.947 1.36963C168.359 1.36963 173.404 6.62901 173.404 15.8599C173.404 25.0459 168.359 30.4326 161.947 30.4326Z" fill="white"/>
    </svg>
);


export default function LandingPage() {
  return (
    <div className="bg-background text-foreground">
      <header className="py-4 px-4 sm:px-8 lg:px-16 flex justify-between items-center border-b">
        <div className="flex items-center gap-2">
          <NovainLogo />
        </div>
        <nav className="hidden lg:flex items-center gap-8">
          <a href="#" className="text-sm font-medium text-cyan-500 border-b-2 border-cyan-500 pb-1">
            Home
          </a>
          <a href="#" className="text-sm font-medium text-gray-600 hover:text-cyan-500">
            Blog
          </a>
          <a href="#" className="text-sm font-medium text-gray-600 hover:text-cyan-500">
            About Us
          </a>
          <a href="#" className="text-sm font-medium text-gray-600 hover:text-cyan-500">
            Contact Us
          </a>
        </nav>
        <div className="hidden sm:flex items-center gap-4">
          <Button style={{ backgroundColor: '#D90067', color: 'white', borderRadius: '9999px', padding: '0 24px' }}>
            Emergency
          </Button>
          <Link href="/general-login" passHref>
            <Button style={{ backgroundColor: '#46C8F5', color: 'white', borderRadius: '8px', padding: '0 24px' }} asChild>
              <span>LOGIN/SIGN UP</span>
            </Button>
          </Link>
        </div>
        <div className="lg:hidden">
          <Sheet>
            <SheetTrigger asChild>
              <Button variant="ghost" size="icon">
                <Menu className="h-6 w-6" />
              </Button>
            </SheetTrigger>
            <SheetContent side="left">
              <SheetHeader>
                <SheetTitle className="sr-only">Mobile Menu</SheetTitle>
              </SheetHeader>
              <nav className="flex flex-col gap-4 mt-8">
                <a href="#" className="text-lg font-medium text-cyan-500">
                  Home
                </a>
                <a href="#" className="text-lg font-medium text-gray-600 hover:text-cyan-500">
                  Blog
                </a>
                <a href="#" className="text-lg font-medium text-gray-600 hover:text-cyan-500">
                  About Us
                </a>
                <a href="#" className="text-lg font-medium text-gray-600 hover:text-cyan-500">
                  Contact Us
                </a>
                <Button style={{ backgroundColor: '#D90067', color: 'white', borderRadius: '9999px', marginTop: '1rem' }}>
                  Emergency
                </Button>
                <Link href="/general-login" passHref>
                  <Button style={{ backgroundColor: '#46C8F5', color: 'white', borderRadius: '8px', width: '100%' }} asChild>
                    <span>LOGIN/SIGN UP</span>
                  </Button>
                </Link>
              </nav>
            </SheetContent>
          </Sheet>
        </div>
      </header>

      <main>
        <section className="relative py-24 sm:py-32 lg:py-40 text-center bg-cover bg-center" style={{ backgroundImage: "url('https://placehold.co/1600x800.png')" }} data-ai-hint="medical team">
          <div className="absolute inset-0 bg-white/50" />
          <div className="relative z-10 px-4">
            <h2 className="text-4xl sm:text-5xl lg:text-6xl font-bold text-black font-serif">
              Get Professional Medical<br/>Assistance Anytime, Anywhere
            </h2>
            <p className="mt-4 max-w-3xl mx-auto text-lg text-black">
              Connect with trusted medical professionals from your smartphone and get the care you need when you need it most.
            </p>
            <div className="mt-8 max-w-4xl mx-auto grid grid-cols-1 sm:grid-cols-2 gap-4 items-start bg-white p-4 rounded-lg shadow-lg">
              <div>
                <div className="relative">
                  <MapPin className="absolute left-3 top-1/2 -translate-y-1/2 h-5 w-5 text-gray-400" />
                  <Input
                    type="text"
                    placeholder="Search Location"
                    className="pl-10 text-gray-900 border-r-0"
                  />
                </div>
                <p className="text-xs text-gray-500 mt-1 text-left">Based on your Location</p>
              </div>
              <div className="flex flex-col">
                  <div className="flex gap-2">
                    <div className="relative flex-grow">
                      <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-5 w-5 text-gray-400" />
                      <Input
                          type="text"
                          placeholder="Search Doctors, Clinics, Hospitals, Diseases, Specialization, etc"
                          className="pl-10 flex-grow text-gray-900"
                      />
                    </div>
                    <Button size="icon" style={{ backgroundColor: '#D90067' }}>
                      <Search className="h-5 w-5" />
                    </Button>
                  </div>
                  <p className="text-xs text-gray-500 mt-1 text-left">Example: Dentist, Sugar checkup, Blood test, Neurosurgeon, etc</p>
              </div>
            </div>
          </div>
        </section>
        
        <section className="py-16 px-4 sm:px-8 lg:px-16">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8 items-start">
            <div className="md:col-span-1">
              <p className="text-sm font-semibold text-blue-500">SERVICES</p>
              <h3 className="text-4xl font-bold mt-2">
                Hospitals, Clinics and Specialists
              </h3>
            </div>
            <div className="md:col-span-2">
                 <p className="text-muted-foreground">
                Access our extensive network of accredited medical facilities offering specialized treatments, routine check-ups, and personalized care. Find the best healthcare options tailored to your needs, ensuring convenience, reliability, and expert medical attention.
                </p>
            </div>
          </div>
          <div className="mt-12 grid grid-cols-2 sm:grid-cols-3 md:grid-cols-5 gap-8 text-center">
            {[
              { icon: DentistIcon, label: "Dentist" },
              { icon: Brain, label: "Neurology" },
              { icon: UrologyIcon, label: "Urology" },
              { icon: CardiologyIcon, label: "Cardiology" },
              { icon: OrthopedicsIcon, label: "Orthopedics" },
            ].map((item, index) => (
              <div key={index} className="flex flex-col items-center gap-3">
                <div className="w-24 h-24 rounded-full border-2 flex items-center justify-center bg-card">
                  <item.icon className="w-12 h-12 text-gray-700" />
                </div>
                 <div className="w-4 h-4 rounded-full bg-cyan-400 -mt-4" />
                <p className="font-semibold mt-2">{item.label}</p>
              </div>
            ))}
          </div>
        </section>

        <section className="py-16 px-4 sm:px-8 lg:px-16 bg-pink-50">
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-8 items-start">
            <div className="lg:col-span-1">
                <h3 className="text-3xl font-bold">
                Trusted, Verified Medical Experts at Your Fingertips
                </h3>
                <p className="mt-4 text-muted-foreground text-sm">
                Our network includes certified doctors and healthcare professionals with diverse expertise, from general practitioners to specialists, ready to help you on your journey to living a healthy life. Our medical professionals are rigorously vetted to ensure you receive the highest standard of care; each doctor is fully licensed and certified in their field, bringing years of experience and dedication to patient well-being.
                </p>
                <Button className="mt-6" style={{ backgroundColor: '#38bdf8' }}>Read More</Button>
            </div>

            <div className="lg:col-span-2 relative">
                <div className="absolute left-0 top-1/2 -translate-y-1/2 -translate-x-4 z-10">
                    <Button variant="ghost" size="icon" className="bg-white rounded-full shadow-md w-8 h-8 flex items-center justify-center">
                        <ChevronLeft className="h-5 w-5" />
                    </Button>
                </div>
                 <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-4">
                    {[
                      {
                        name: "Blossom Efe",
                        specialty: "MDS - Periodontology and oral implantology, 2015",
                        image: "https://placehold.co/250x250.png",
                        hint: "male doctor",
                        verified: true,
                        rating: 5,
                        reviews: 29,
                        location: "Florida, USA",
                        availability: "Available on Friday, 22nd March",
                        price: "$200 - $500"
                      },
                      {
                        name: "Leke Alder",
                        specialty: "MDS - Periodontology and oral implantology, 2015",
                        image: "https://placehold.co/250x250.png",
                        hint: "doctor portrait",
                        verified: true,
                        rating: 5,
                        reviews: 97,
                        location: "Florida, USA",
                        availability: "Available on Friday, 22nd March",
                        price: "$200 - $500"
                      },
                      {
                        name: "Chiaom Agu",
                        specialty: "MDS - Periodontology and oral implantology, 2015",
                        image: "https://placehold.co/250x250.png",
                        hint: "female doctor",
                        verified: true,
                        rating: 5,
                        reviews: 97,
                        location: "Florida, USA",
                        availability: "Available on Friday, 22nd March",
                        price: "$200 - $500"
                      },
                    ].map((doctor, index) => (
                      <div
                        key={index}
                        className="bg-white rounded-lg shadow-md p-4 flex flex-col"
                      >
                        <img
                          src={doctor.image}
                          alt={doctor.name}
                          className="w-full h-40 object-cover rounded-md"
                          data-ai-hint={doctor.hint}
                        />
                        <div className="flex items-center mt-3">
                            <h4 className="text-md font-bold">{doctor.name}</h4>
                            {doctor.verified && <CheckCircle2 className="w-4 h-4 text-green-500 ml-1" />}
                        </div>
                        <p className="text-muted-foreground text-xs mt-1">{doctor.specialty}</p>
                        <div className="flex items-center mt-2">
                          <div className="flex text-yellow-400">
                            {[...Array(doctor.rating)].map((_, i) => (
                              <svg key={i} className="w-4 h-4" fill="currentColor" viewBox="0 0 20 20" ><path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.286 3.957a1 1 0 00.95.69h4.162c.969 0 1.371 1.24.588 1.81l-3.368 2.448a1 1 0 00-.364 1.118l1.287 3.957c.3.921-.755 1.688-1.539 1.118l-3.368-2.448a1 1 0 00-1.176 0l-3.368 2.448c-.783.57-1.838-.197-1.539-1.118l1.287-3.957a1 1 0 00-.364-1.118L2.24 9.384c-.783-.57-.38-1.81.588-.81h4.162a1 1 0 00.95-.69L9.049 2.927z" /></svg>
                            ))}
                          </div>
                          <span className="text-xs text-muted-foreground ml-1">({doctor.reviews})</span>
                        </div>
                         <div className="mt-3 space-y-2 text-xs text-muted-foreground">
                            <div className="flex items-center gap-2"><MapPin className="w-3.5 h-3.5" /><span>{doctor.location}</span></div>
                            <div className="flex items-center gap-2"><Calendar className="w-3.5 h-3.5" /><span>{doctor.availability}</span></div>
                            <div className="flex items-center gap-2"><Clock className="w-3.5 h-3.5" /><span>{doctor.price}</span></div>
                        </div>

                        <div className="mt-4 flex gap-2 w-full">
                          <Button variant="outline" className="w-full text-cyan-500 border-cyan-500">
                            View Profile
                          </Button>
                          <Button className="w-full" style={{ backgroundColor: '#38bdf8' }}>Book Now</Button>
                        </div>
                      </div>
                    ))}
                </div>
                 <div className="absolute right-0 top-1/2 -translate-y-1/2 translate-x-4 z-10">
                    <Button variant="ghost" size="icon" className="bg-white rounded-full shadow-md w-8 h-8 flex items-center justify-center">
                        <ChevronRight className="h-5 w-5" />
                    </Button>
                </div>
            </div>
          </div>
        </section>

        <section className="relative py-24 sm:py-32 lg:py-40 text-center text-white bg-cover bg-center" style={{ backgroundImage: "url('https://placehold.co/1600x600.png')" }} data-ai-hint="doctor smiling">
          <div className="absolute inset-0 bg-black/60" />
          <div className="relative z-10 px-4">
            <h3 className="text-4xl font-bold">24/7 Real-Time Emergency Care</h3>
            <p className="mt-4 max-w-3xl mx-auto text-lg">
              In an emergency, every second counts. Connect instantly with our doctors and specialists for urgent medical help and advice, available 24/7, wherever you are.
            </p>
          </div>
        </section>

        <section className="py-16 px-4 sm:px-8 lg:px-16 bg-gray-50">
          <div className="text-center mb-12">
            <h3 className="text-3xl font-bold">Get Urgent Medical Help, Fast</h3>
            <p className="mt-4 max-w-3xl mx-auto text-muted-foreground">
              Avoid the chaos and long lines. Our app connects you to emergency-certified doctors in minutes - 24/7 access, zero hassle.
            </p>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
            {[
              "Abdominal pain", "Mental health concerns", "Ear infection",
              "Anxieties/stress", "Red eye", "Pain relief",
              "Allergy", "Prescription refill", "Chest infection",
              "Nausea/Vomiting", "Asthma attack", "Malaria",
              "Diarrhea", "Migraine/Headaches", "Others",
            ].map((service, index) => (
              <div
                key={index}
                className="flex justify-between items-center p-4 border rounded-lg bg-white shadow-sm"
              >
                <span>{service}</span>
                <button className="w-8 h-8 rounded-full bg-blue-100 text-blue-500 flex items-center justify-center">
                    <ChevronRight className="h-5 w-5" />
                </button>
              </div>
            ))}
          </div>
        </section>

        <section className="py-16 px-4 sm:px-8 lg:px-16 bg-blue-50">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
            <div>
              <h3 className="text-4xl font-bold">
                Your World of Care, Now In Your Pocket
              </h3>
              <p className="mt-6 text-muted-foreground">
                Download the Hovain app to get all your healthcare needs in one place. You can book appointments, consult with doctors, get prescriptions, and more.
              </p>
              <div className="mt-8 flex gap-4">
                <img src="https://placehold.co/150x50.png" alt="App Store" data-ai-hint="app store" />
                <img src="https://placehold.co/150x50.png" alt="Google Play" data-ai-hint="google play" />
              </div>
            </div>
            <div>
              <img
                src="https://placehold.co/600x400.png"
                alt="Doctor with phone"
                className="rounded-lg shadow-lg"
                data-ai-hint="doctor phone"
              />
            </div>
          </div>
        </section>

        <section className="py-16 px-4 sm:px-8 lg:px-16">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
            <div>
              <img
                src="https://placehold.co/600x400.png"
                alt="Hospital room"
                className="rounded-lg shadow-lg"
                data-ai-hint="hospital room"
              />
            </div>
            <div>
              <h3 className="text-3xl font-bold">
                Available Features In Our Partner Clinics
              </h3>
              <p className="mt-4 text-muted-foreground">
                Our partner clinics are equipped with state-of-the-art facilities and offer a wide range of services to provide you with the best possible care.
              </p>
              <div className="mt-8 flex gap-8">
                <div className="text-center">
                  <img src="https://placehold.co/100x100.png" alt="Feature 1" className="rounded-full mx-auto" data-ai-hint="medical equipment" />
                  <p className="mt-2 font-semibold">24/7 Doctors</p>
                </div>
                <div className="text-center">
                  <img src="https://placehold.co/100x100.png" alt="Feature 2" className="rounded-full mx-auto" data-ai-hint="lab test" />
                  <p className="mt-2 font-semibold">Lab Testing</p>
                </div>
                <div className="text-center">
                  <img src="https://placehold.co/100x100.png" alt="Feature 3" className="rounded-full mx-auto" data-ai-hint="medical technology" />
                  <p className="mt-2 font-semibold">Modern Technology</p>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>

      <footer style={{ backgroundColor: '#0A2540' }} className="text-gray-300 py-12 px-4 sm:px-8 lg:px-16 relative">
          <div className="absolute right-0 bottom-0">
            <svg width="250" height="250" viewBox="0 0 250 250" fill="none" xmlns="http://www.w3.org/2000/svg">
              <path d="M250 250V0C111.929 0 0 111.929 0 250H250Z" fill="#103A63"/>
            </svg>
          </div>
        <div className="grid grid-cols-1 md:grid-cols-5 gap-8 relative z-10">
          <div className="md:col-span-2">
            <NovainLogoWhite />
            <p className="mt-4 text-sm max-w-md">
              Bringing quality healthcare to your fingertips. Novain Health connects you with trusted medical professionals anytime, anywhere, so you’re never alone on your health journey. Our mission is to make professional medical assistance accessible to all by connecting patients with certified doctors and healthcare professionals anytime, anywhere.
            </p>
            <div className="flex space-x-4 mt-6">
              <a href="#"><img src="https://placehold.co/32x32.png" alt="Facebook" data-ai-hint="social icon"/></a>
              <a href="#"><img src="https://placehold.co/32x32.png" alt="Dribbble" data-ai-hint="social icon"/></a>
              <a href="#"><img src="https://placehold.co/32x32.png" alt="LinkedIn" data-ai-hint="social icon"/></a>
              <a href="#"><img src="https://placehold.co/32x32.png" alt="Behance" data-ai-hint="social icon"/></a>
            </div>
          </div>
          <div>
            <h4 className="font-bold text-white">About</h4>
            <ul className="mt-4 space-y-2 text-sm">
              <li><a href="#" className="hover:text-white">About Us</a></li>
              <li><a href="#" className="hover:text-white">How It Works</a></li>
              <li><a href="#" className="hover:text-white">For Patients</a></li>
              <li><a href="#" className="hover:text-white">For Doctors</a></li>
            </ul>
             <h4 className="font-bold text-white mt-8">Support</h4>
            <ul className="mt-4 space-y-2 text-sm">
              <li><a href="#" className="hover:text-white">FAQs</a></li>
              <li><a href="#" className="hover:text-white">Help Center</a></li>
              <li><a href="#" className="hover:text-white">Emergency Response Info</a></li>
            </ul>
          </div>
          <div>
            <h4 className="font-bold text-white">Download the App</h4>
            <div className="mt-4 space-y-4">
              <a href="#"><img src="https://placehold.co/135x40.png" alt="App Store" data-ai-hint="app store button"/></a>
              <a href="#"><img src="https://placehold.co/135x40.png" alt="Google Play" data-ai-hint="google play button"/></a>
            </div>
          </div>
          <div>
            <h4 className="font-bold text-white">Contact Us</h4>
            <ul className="mt-4 space-y-4 text-sm">
              <li className="flex items-start gap-3">
                  <MapPin className="w-5 h-5 mt-1"/>
                  <span>3556 Beech Street, San Francisco, California, CA 94108</span>
              </li>
              <li className="flex items-center gap-3">
                  <Mail className="w-5 h-5" />
                  <a href="mailto:doccure@example.com" className="hover:text-white">doccure@example.com</a>
              </li>
              <li className="flex items-center gap-3">
                  <Phone className="w-5 h-5" />
                  <a href="tel:+13153695943" className="hover:text-white">+1 315 369 5943</a>
              </li>
            </ul>
          </div>
        </div>
        <div className="mt-12 pt-8 border-t border-gray-700 flex justify-between items-center text-sm relative z-10">
          <p>&copy; 2024 Novain Health. All Rights Reserved.</p>
          <div className="flex space-x-6">
            <a href="#" className="hover:text-white">Data Protection Policy</a>
            <a href="#" className="hover:text-white">Privacy Policy</a>
            <a href="#" className="hover:text-white">Terms and Conditions</a>
          </div>
        </div>
      </footer>
    </div>
  );
}
