
/**
 * This code was generated by Builder.io.
 */
"use client";

import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import Link from "next/link";
import {
  Brain,
  Search,
  ChevronRight,
  CheckCircle2,
  Calendar,
  Clock,
  MapPin,
  ChevronLeft,
} from "lucide-react";
import LandingHeader from "./landing-header";
import LandingFooter from "./landing-footer";

const DentistIcon = (props: React.SVGProps<SVGSVGElement>) => (
  <svg
    {...props}
    xmlns="http://www.w3.org/2000/svg"
    width="48"
    height="48"
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth="1.5"
    strokeLinecap="round"
    strokeLinejoin="round"
  >
    <path d="M12.485 2.49a.5.5 0 0 0-.485.51v.002l-2.999 6c-.03.06-.06.12-.08.18L8.9 9.2a.5.5 0 0 0-.02.2v8.1a1.5 1.5 0 0 0 1.5 1.5h4.24a1.5 1.5 0 0 0 1.5-1.5V9.4a.5.5 0 0 0-.02-.2l-.022-.04-2.999-6a.5.5 0 0 0-.485-.51Z" />
    <path d="M12.485 18v-4.5" />
    <path d="M12.485 2.5a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5Z" />
  </svg>
);

const UrologyIcon = (props: React.SVGProps<SVGSVGElement>) => (
  <svg
    {...props}
    xmlns="http://www.w3.org/2000/svg"
    width="48"
    height="48"
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth="1.5"
    strokeLinecap="round"
    strokeLinejoin="round"
  >
    <path d="M10.22 6.31C9.44 5.53 8.32 5 7 5c-2.76 0-5 2.24-5 5s2.24 5 5 5c1.32 0 2.44-.53 3.22-1.31" />
    <path d="M13.78 6.31C14.56 5.53 15.68 5 17 5c2.76 0 5 2.24 5 5s-2.24 5-5 5c-1.32 0-2.44-.53-3.22-1.31" />
    <path d="M15.5 12.5c0 2.48-1.57 4.5-3.5 4.5s-3.5-2.02-3.5-4.5" />
  </svg>
);

const CardiologyIcon = (props: React.SVGProps<SVGSVGElement>) => (
  <svg
    {...props}
    width="48"
    height="48"
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth="1.5"
    strokeLinecap="round"
    strokeLinejoin="round"
  >
    <path d="M12 20.84l-1.41-1.41C5.63 14.47 2 11.25 2 7.5 2 4.42 4.42 2 7.5 2c1.74 0 3.41.81 4.5 2.09C13.09 2.81 14.76 2 16.5 2 19.58 2 22 4.42 22 7.5c0 3.75-3.63 6.97-8.59 11.93L12 20.84z" />
  </svg>
);

const OrthopedicsIcon = (props: React.SVGProps<SVGSVGElement>) => (
    <svg 
    {...props}
    width="48"
    height="48"
    viewBox="0 0 24 24" 
    fill="none" 
    stroke="currentColor" 
    strokeWidth="1.5" 
    strokeLinecap="round" 
    strokeLinejoin="round">
        <path d="M10 6.605a1 1 0 0 1 1.638-.77l4 5a1 1 0 0 1 0 1.54l-4 5A1 1 0 0 1 10 16.605V6.605z" />
        <path d="M6 7h1" />
        <path d="M6 12h1" />
        <path d="M6 17h1" />
    </svg>
);


export default function LandingPage() {
  return (
    <div className="bg-background text-foreground">
      <LandingHeader />

      <main>
        <section className="relative py-24 sm:py-32 lg:py-40 text-center bg-cover bg-center" style={{ backgroundImage: "url('https://placehold.co/1600x800.png')" }} data-ai-hint="medical team">
          <div className="absolute inset-0 bg-white/50" />
          <div className="relative z-10 px-4">
            <h2 className="text-4xl sm:text-5xl lg:text-6xl font-bold text-black font-serif">
              Get Professional Medical<br/>Assistance Anytime, Anywhere
            </h2>
            <p className="mt-4 max-w-3xl mx-auto text-lg text-black">
              Connect with trusted medical professionals from your smartphone and get the care you need when you need it most.
            </p>
            <div className="mt-8 max-w-4xl mx-auto grid grid-cols-1 sm:grid-cols-2 gap-4 items-start bg-white p-4 rounded-lg shadow-lg">
              <div>
                <div className="relative">
                  <MapPin className="absolute left-3 top-1/2 -translate-y-1/2 h-5 w-5 text-gray-400" />
                  <Input
                    type="text"
                    placeholder="Search Location"
                    className="pl-10 text-gray-900 border-r-0"
                  />
                </div>
                <p className="text-xs text-gray-500 mt-1 text-left">Based on your Location</p>
              </div>
              <div className="flex flex-col">
                  <div className="flex gap-2">
                    <div className="relative flex-grow">
                      <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-5 w-5 text-gray-400" />
                      <Input
                          type="text"
                          placeholder="Search Doctors, Clinics, Hospitals, Diseases, Specialization, etc"
                          className="pl-10 flex-grow text-gray-900"
                      />
                    </div>
                    <Button type="button" size="icon" style={{ backgroundColor: '#D90067' }}>
                      <Search className="h-5 w-5" />
                    </Button>
                  </div>
                  <p className="text-xs text-gray-500 mt-1 text-left">Example: Dentist, Sugar checkup, Blood test, Neurosurgeon, etc</p>
              </div>
            </div>
          </div>
        </section>
        
        <section className="py-16 px-4 sm:px-8 lg:px-16">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8 items-start">
            <div className="md:col-span-1">
              <p className="text-sm font-semibold text-blue-500">SERVICES</p>
              <h3 className="text-4xl font-bold mt-2">
                Hospitals, Clinics and Specialists
              </h3>
            </div>
            <div className="md:col-span-2">
                 <p className="text-muted-foreground">
                Access our extensive network of accredited medical facilities offering specialized treatments, routine check-ups, and personalized care. Find the best healthcare options tailored to your needs, ensuring convenience, reliability, and expert medical attention.
                </p>
            </div>
          </div>
          <div className="mt-12 grid grid-cols-2 sm:grid-cols-3 md:grid-cols-5 gap-8 text-center">
            {[
              { icon: DentistIcon, label: "Dentist" },
              { icon: Brain, label: "Neurology" },
              { icon: UrologyIcon, label: "Urology" },
              { icon: CardiologyIcon, label: "Cardiology" },
              { icon: OrthopedicsIcon, label: "Orthopedics" },
            ].map((item, index) => (
              <div key={index} className="flex flex-col items-center gap-3">
                <div className="w-24 h-24 rounded-full border-2 flex items-center justify-center bg-card">
                  <item.icon className="w-12 h-12 text-gray-700" />
                </div>
                 <div className="w-4 h-4 rounded-full bg-cyan-400 -mt-4" />
                <p className="font-semibold mt-2">{item.label}</p>
              </div>
            ))}
          </div>
        </section>

        <section className="py-16 px-4 sm:px-8 lg:px-16 bg-pink-50">
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-8 items-start">
            <div className="lg:col-span-1">
                <h3 className="text-3xl font-bold">
                Trusted, Verified Medical Experts at Your Fingertips
                </h3>
                <p className="mt-4 text-muted-foreground text-sm">
                Our network includes certified doctors and healthcare professionals with diverse expertise, from general practitioners to specialists, ready to help you on your journey to living a healthy life. Our medical professionals are rigorously vetted to ensure you receive the highest standard of care; each doctor is fully licensed and certified in their field, bringing years of experience and dedication to patient well-being.
                </p>
                <Button type="button" className="mt-6" style={{ backgroundColor: '#38bdf8' }}>Read More</Button>
            </div>

            <div className="lg:col-span-2 relative">
                <div className="absolute left-0 top-1/2 -translate-y-1/2 -translate-x-4 z-10">
                    <Button type="button" variant="ghost" size="icon" className="bg-white rounded-full shadow-md w-8 h-8 flex items-center justify-center">
                        <ChevronLeft className="h-5 w-5" />
                    </Button>
                </div>
                 <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-4">
                    {[
                      {
                        name: "Blossom Efe",
                        specialty: "MDS - Periodontology and oral implantology, 2015",
                        image: "https://placehold.co/250x250.png",
                        hint: "male doctor",
                        verified: true,
                        rating: 5,
                        reviews: 29,
                        location: "Florida, USA",
                        availability: "Available on Friday, 22nd March",
                        price: "₦200 - ₦500"
                      },
                      {
                        name: "Leke Alder",
                        specialty: "MDS - Periodontology and oral implantology, 2015",
                        image: "https://placehold.co/250x250.png",
                        hint: "doctor portrait",
                        verified: true,
                        rating: 5,
                        reviews: 97,
                        location: "Florida, USA",
                        availability: "Available on Friday, 22nd March",
                        price: "₦200 - ₦500"
                      },
                      {
                        name: "Chiaom Agu",
                        specialty: "MDS - Periodontology and oral implantology, 2015",
                        image: "https://placehold.co/250x250.png",
                        hint: "female doctor",
                        verified: true,
                        rating: 5,
                        reviews: 97,
                        location: "Florida, USA",
                        availability: "Available on Friday, 22nd March",
                        price: "₦200 - ₦500"
                      },
                    ].map((doctor, index) => (
                      <div
                        key={index}
                        className="bg-white rounded-lg shadow-md p-4 flex flex-col"
                      >
                        <img
                          src={doctor.image}
                          alt={doctor.name}
                          className="w-full h-40 object-cover rounded-md"
                          data-ai-hint={doctor.hint}
                        />
                        <div className="flex items-center mt-3">
                            <h4 className="text-md font-bold">{doctor.name}</h4>
                            {doctor.verified && <CheckCircle2 className="w-4 h-4 text-green-500 ml-1" />}
                        </div>
                        <p className="text-muted-foreground text-xs mt-1">{doctor.specialty}</p>
                        <div className="flex items-center mt-2">
                          <div className="flex text-yellow-400">
                            {[...Array(doctor.rating)].map((_, i) => (
                              <svg key={i} className="w-4 h-4" fill="currentColor" viewBox="0 0 20 20" ><path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.286 3.957a1 1 0 00.95.69h4.162c.969 0 1.371 1.24.588 1.81l-3.368 2.448a1 1 0 00-.364 1.118l1.287 3.957c.3.921-.755 1.688-1.539 1.118l-3.368-2.448a1 1 0 00-1.176 0l-3.368 2.448c-.783.57-1.838-.197-1.539-1.118l1.287-3.957a1 1 0 00-.364-1.118L2.24 9.384c-.783-.57-.38-1.81.588-.81h4.162a1 1 0 00.95-.69L9.049 2.927z" /></svg>
                            ))}
                          </div>
                          <span className="text-xs text-muted-foreground ml-1">({doctor.reviews})</span>
                        </div>
                         <div className="mt-3 space-y-2 text-xs text-muted-foreground">
                            <div className="flex items-center gap-2"><MapPin className="w-3.5 h-3.5" /><span>{doctor.location}</span></div>
                            <div className="flex items-center gap-2"><Calendar className="w-3.5 h-3.5" /><span>{doctor.availability}</span></div>
                            <div className="flex items-center gap-2"><Clock className="w-3.5 h-3.5" /><span>{doctor.price}</span></div>
                        </div>

                        <div className="mt-4 flex gap-2 w-full">
                          <Button type="button" variant="outline" className="w-full text-cyan-500 border-cyan-500">
                            View Profile
                          </Button>
                          <Button type="button" className="w-full" style={{ backgroundColor: '#38bdf8' }}>Book Now</Button>
                        </div>
                      </div>
                    ))}
                </div>
                 <div className="absolute right-0 top-1/2 -translate-y-1/2 translate-x-4 z-10">
                    <Button type="button" variant="ghost" size="icon" className="bg-white rounded-full shadow-md w-8 h-8 flex items-center justify-center">
                        <ChevronRight className="h-5 w-5" />
                    </Button>
                </div>
            </div>
          </div>
        </section>

        <section className="relative py-24 sm:py-32 lg:py-40 text-center text-white bg-cover bg-center" style={{ backgroundImage: "url('https://placehold.co/1600x600.png')" }} data-ai-hint="doctor smiling">
          <div className="absolute inset-0 bg-black/60" />
          <div className="relative z-10 px-4">
            <h3 className="text-4xl font-bold">24/7 Real-Time Emergency Care</h3>
            <p className="mt-4 max-w-3xl mx-auto text-lg">
              In an emergency, every second counts. Connect instantly with our doctors and specialists for urgent medical help and advice, available 24/7, wherever you are.
            </p>
          </div>
        </section>

        <section className="py-16 px-4 sm:px-8 lg:px-16 bg-gray-50">
          <div className="text-center mb-12">
            <h3 className="text-3xl font-bold">Get Urgent Medical Help, Fast</h3>
            <p className="mt-4 max-w-3xl mx-auto text-muted-foreground">
              Avoid the chaos and long lines. Our app connects you to emergency-certified doctors in minutes - 24/7 access, zero hassle.
            </p>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
            {[
              "Abdominal pain", "Mental health concerns", "Ear infection",
              "Anxieties/stress", "Red eye", "Pain relief",
              "Allergy", "Prescription refill", "Chest infection",
              "Nausea/Vomiting", "Asthma attack", "Malaria",
              "Diarrhea", "Migraine/Headaches", "Others",
            ].map((service, index) => (
              <div
                key={index}
                className="flex justify-between items-center p-4 border rounded-lg bg-white shadow-sm"
              >
                <span>{service}</span>
                <Button
                  type="button"
                  variant="ghost"
                  size="icon"
                  className="w-8 h-8 rounded-full bg-blue-100 text-blue-500 hover:bg-blue-200"
                >
                    <ChevronRight className="h-5 w-5" />
                </Button>
              </div>
            ))}
          </div>
        </section>

        <section className="py-16 px-4 sm:px-8 lg:px-16 bg-blue-50">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
            <div>
              <h3 className="text-4xl font-bold">
                Your World of Care, Now In Your Pocket
              </h3>
              <p className="mt-6 text-muted-foreground">
                Download the Hovain app to get all your healthcare needs in one place. You can book appointments, consult with doctors, get prescriptions, and more.
              </p>
              <div className="mt-8 flex gap-4">
                <img src="https://placehold.co/150x50.png" alt="App Store" data-ai-hint="app store" />
                <img src="https://placehold.co/150x50.png" alt="Google Play" data-ai-hint="google play" />
              </div>
            </div>
            <div>
              <img
                src="https://placehold.co/600x400.png"
                alt="Doctor with phone"
                className="rounded-lg shadow-lg"
                data-ai-hint="doctor phone"
              />
            </div>
          </div>
        </section>

        <section className="py-16 px-4 sm:px-8 lg:px-16">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
            <div>
              <img
                src="https://placehold.co/600x400.png"
                alt="Hospital room"
                className="rounded-lg shadow-lg"
                data-ai-hint="hospital room"
              />
            </div>
            <div>
              <h3 className="text-3xl font-bold">
                Available Features In Our Partner Clinics
              </h3>
              <p className="mt-4 text-muted-foreground">
                Our partner clinics are equipped with state-of-the-art facilities and offer a wide range of services to provide you with the best possible care.
              </p>
              <div className="mt-8 flex gap-8">
                <div className="text-center">
                  <img src="https://placehold.co/100x100.png" alt="Feature 1" className="rounded-full mx-auto" data-ai-hint="medical equipment" />
                  <p className="mt-2 font-semibold">24/7 Doctors</p>
                </div>
                <div className="text-center">
                  <img src="https://placehold.co/100x100.png" alt="Feature 2" className="rounded-full mx-auto" data-ai-hint="lab test" />
                  <p className="mt-2 font-semibold">Lab Testing</p>
                </div>
                <div className="text-center">
                  <img src="https://placehold.co/100x100.png" alt="Feature 3" className="rounded-full mx-auto" data-ai-hint="medical technology" />
                  <p className="mt-2 font-semibold">Modern Technology</p>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>

      <LandingFooter />
    </div>
  );
}
