/**
 * This code was generated by Builder.io.
 */
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import {
  Brain,
  HeartPulse,
  Search,
  Stethoscope,
  ChevronRight,
} from "lucide-react";

const DentistIcon = (props: React.SVGProps<SVGSVGElement>) => (
  <svg
    {...props}
    xmlns="http://www.w3.org/2000/svg"
    width="24"
    height="24"
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth="2"
    strokeLinecap="round"
    strokeLinejoin="round"
  >
    <path d="M10.2 2.5c-.2.2-.4.5-.5.8l-2.2 4.4c-.1.2-.2.4-.2.6v8.4c0 .8.7 1.5 1.5 1.5h8.4c.8 0 1.5-.7 1.5-1.5v-8.4c0-.2-.1-.4-.2-.6L16.3 3.3c-.1-.3-.3-.6-.5-.8-.3-.3-.7-.5-1.1-.5h-3c-.4 0-.8.2-1.1.5Z" />
    <path d="M12 18v-4" />
    <path d="M12 2.5a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5Z" />
  </svg>
);

const UrologyIcon = (props: React.SVGProps<SVGSVGElement>) => (
  <svg
    {...props}
    xmlns="http://www.w3.org/2000/svg"
    width="24"
    height="24"
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth="2"
    strokeLinecap="round"
    strokeLinejoin="round"
  >
    <path d="M10.22 6.31C9.44 5.53 8.32 5 7 5c-2.76 0-5 2.24-5 5s2.24 5 5 5c1.32 0 2.44-.53 3.22-1.31" />
    <path d="M13.78 6.31C14.56 5.53 15.68 5 17 5c2.76 0 5 2.24 5 5s-2.24 5-5 5c-1.32 0-2.44-.53-3.22-1.31" />
    <path d="M15.5 12.5c0 2.48-1.57 4.5-3.5 4.5s-3.5-2.02-3.5-4.5" />
  </svg>
);

const OncologyIcon = (props: React.SVGProps<SVGSVGElement>) => (
  <svg
    {...props}
    xmlns="http://www.w3.org/2000/svg"
    width="24"
    height="24"
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth="2"
    strokeLinecap="round"
    strokeLinejoin="round"
  >
    <path d="M14.5 17.5C12.5863 17.5 11 15.9137 11 14C11 12.0863 12.5863 10.5 14.5 10.5C16.4137 10.5 18 12.0863 18 14C18 15.9137 16.4137 17.5 14.5 17.5Z" />
    <path d="M12.5 7.5C10.5863 7.5 9 5.91371 9 4C9 2.08629 10.5863 0.5 12.5 0.5C14.4137 0.5 16 2.08629 16 4C16 5.91371 14.4137 7.5 12.5 7.5Z" />
    <path d="M6 14C7.65685 14 9 12.6569 9 11C9 9.34315 7.65685 8 6 8C4.34315 8 3 9.34315 3 11C3 12.6569 4.34315 14 6 14Z" />
    <path d="M19 12C20.6569 12 22 10.6569 22 9C22 7.34315 20.6569 6 19 6C17.3431 6 16 7.34315 16 9C16 10.6569 17.3431 12 19 12Z" />
    <path d="M6 22C7.65685 22 9 20.6569 9 19C9 17.3431 7.65685 16 6 16C4.34315 16 3 17.3431 3 19C3 20.6569 4.34315 22 6 22Z" />
  </svg>
);

export default function LandingPage() {
  return (
    <div className="bg-background text-foreground">
      <header className="py-4 px-4 sm:px-8 lg:px-16 flex justify-between items-center border-b">
        <div className="flex items-center gap-2">
          <HeartPulse className="w-8 h-8 text-pink-500" />
          <h1 className="text-2xl font-bold">NovainHealth</h1>
        </div>
        <nav className="hidden lg:flex items-center gap-6">
          <a href="#" className="text-sm font-medium hover:text-pink-500">
            Home
          </a>
          <a href="#" className="text-sm font-medium hover:text-pink-500">
            Blog
          </a>
          <a href="#" className="text-sm font-medium hover:text-pink-500">
            About Us
          </a>
          <a href="#" className="text-sm font-medium hover:text-pink-500">
            Contact Us
          </a>
        </nav>
        <div className="hidden sm:flex items-center gap-4">
          <Button variant="outline" style={{ borderColor: '#ec4899', color: '#ec4899' }}>
            Enquire
          </Button>
          <Button style={{ backgroundColor: '#0ea5e9', color: 'white' }}>Get Started</Button>
        </div>
      </header>

      <main>
        <section className="relative py-24 sm:py-32 lg:py-40 text-center text-white bg-cover bg-center" style={{ backgroundImage: "url('https://placehold.co/1600x800.png')" }} data-ai-hint="medical team">
          <div className="absolute inset-0 bg-black/50" />
          <div className="relative z-10 px-4">
            <h2 className="text-4xl sm:text-5xl lg:text-6xl font-bold">
              Get Professional Medical Assistance Anytime, Anywhere
            </h2>
            <p className="mt-4 max-w-3xl mx-auto text-lg">
              Connect with trusted medical professionals from your smartphone and get the care you need when you need it most.
            </p>
            <div className="mt-8 max-w-3xl mx-auto grid grid-cols-1 sm:grid-cols-2 gap-4 items-center bg-white p-2 rounded-lg">
              <Input
                type="text"
                placeholder="Enter your location"
                className="text-gray-900"
              />
              <div className="flex gap-2">
                <Input
                  type="text"
                  placeholder="Search for doctors, hospitals..."
                  className="flex-grow text-gray-900"
                />
                <Button size="icon" style={{ backgroundColor: '#ec4899' }}>
                  <Search className="h-5 w-5" />
                </Button>
              </div>
            </div>
          </div>
        </section>

        <section className="py-16 px-4 sm:px-8 lg:px-16">
          <div className="text-center">
            <h3 className="text-3xl font-bold">
              Hospitals, Clinics and Specialists
            </h3>
            <p className="mt-4 max-w-2xl mx-auto text-muted-foreground">
              Because we believe in the importance of health, at Hovain we have gathered the best professionals from different areas to take care of you. You will find more than 1000 doctors from different specialties, and top-tier clinics and hospitals to choose from.
            </p>
          </div>
          <div className="mt-12 grid grid-cols-2 sm:grid-cols-3 md:grid-cols-5 gap-8 text-center">
            {[
              { icon: DentistIcon, label: "Dentist" },
              { icon: Brain, label: "Neurology" },
              { icon: UrologyIcon, label: "Urology" },
              { icon: OncologyIcon, label: "Oncology" },
              { icon: Stethoscope, label: "Cardiologist" },
            ].map((item, index) => (
              <div key={index} className="flex flex-col items-center gap-3">
                <div className="w-24 h-24 rounded-full border-2 flex items-center justify-center bg-card">
                  <item.icon className="w-10 h-10 text-cyan-500" />
                </div>
                <p className="font-semibold">{item.label}</p>
              </div>
            ))}
          </div>
        </section>

        <section className="py-16 px-4 sm:px-8 lg:px-16 bg-pink-50">
          <div className="text-center">
            <h3 className="text-3xl font-bold">
              Trained, Skilled Medical Experts at Your Fingertips
            </h3>
            <p className="mt-4 max-w-2xl mx-auto text-muted-foreground">
              Our team of skilled physicians and specialists provides you with the best medical advice and care. With their vast knowledge and experience, we ensure that you are in good hands.
            </p>
          </div>
          <div className="mt-12 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-8">
            {[
              {
                name: "Dr. Ben Carson",
                specialty: "Neurology",
                rating: 5,
                image: "https://placehold.co/100x100.png",
                hint: "male doctor"
              },
              {
                name: "Dr. John Doe",
                specialty: "Urology",
                rating: 5,
                image: "https://placehold.co/100x100.png",
                hint: "doctor portrait"
              },
              {
                name: "Dr. Emily Taylor",
                specialty: "Cardiology",
                rating: 5,
                image: "https://placehold.co/100x100.png",
                hint: "female doctor"
              },
            ].map((doctor, index) => (
              <div
                key={index}
                className="bg-white rounded-lg shadow-md p-6 flex flex-col items-center text-center"
              >
                <img
                  src={doctor.image}
                  alt={doctor.name}
                  className="w-24 h-24 rounded-full"
                  data-ai-hint={doctor.hint}
                />
                <h4 className="mt-4 text-xl font-bold">{doctor.name}</h4>
                <p className="text-muted-foreground">{doctor.specialty}</p>
                <div className="flex mt-2">
                  {[...Array(doctor.rating)].map((_, i) => (
                    <svg
                      key={i}
                      className="w-5 h-5 text-yellow-400"
                      fill="currentColor"
                      viewBox="0 0 20 20"
                    >
                      <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.286 3.957a1 1 0 00.95.69h4.162c.969 0 1.371 1.24.588 1.81l-3.368 2.448a1 1 0 00-.364 1.118l1.287 3.957c.3.921-.755 1.688-1.539 1.118l-3.368-2.448a1 1 0 00-1.176 0l-3.368 2.448c-.783.57-1.838-.197-1.539-1.118l1.287-3.957a1 1 0 00-.364-1.118L2.24 9.384c-.783-.57-.38-1.81.588-1.81h4.162a1 1 0 00.95-.69L9.049 2.927z" />
                    </svg>
                  ))}
                </div>
                <div className="mt-6 flex gap-4 w-full">
                  <Button variant="outline" className="w-full">
                    View Profile
                  </Button>
                  <Button className="w-full" style={{ backgroundColor: '#0ea5e9' }}>Book Now</Button>
                </div>
              </div>
            ))}
          </div>
        </section>

        <section className="relative py-24 sm:py-32 lg:py-40 text-center text-white bg-cover bg-center" style={{ backgroundImage: "url('https://placehold.co/1600x600.png')" }} data-ai-hint="doctor smiling">
          <div className="absolute inset-0 bg-black/60" />
          <div className="relative z-10 px-4">
            <h3 className="text-4xl font-bold">24/7 Real-Time Emergency Care</h3>
            <p className="mt-4 max-w-3xl mx-auto text-lg">
              In an emergency, every second counts. Connect instantly with our doctors and specialists for urgent medical help and advice, available 24/7, wherever you are.
            </p>
          </div>
        </section>

        <section className="py-16 px-4 sm:px-8 lg:px-16">
          <div className="text-center mb-12">
            <h3 className="text-3xl font-bold">Get Urgent Medical Help, Fast</h3>
            <p className="mt-4 max-w-3xl mx-auto text-muted-foreground">
              Medicine should not be a long-term issue. Get access to emergency services in minutes - 24/7 across your network.
            </p>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
            {[
              "Allergy and immunology", "Emergency medicine", "General practice",
              "Anesthesiology", "Hospice and palliative medicine", "Medical genetics",
              "Dermatology", "Internal medicine", "Neurological surgery",
              "Diagnostic radiology", "Neurology", "Family medicine",
              "Nuclear medicine", "Obstetrics and gynecology"
            ].map((service, index) => (
              <div
                key={index}
                className="flex justify-between items-center p-4 border rounded-lg bg-card shadow-sm"
              >
                <span>{service}</span>
                <ChevronRight className="h-5 w-5 text-muted-foreground" />
              </div>
            ))}
          </div>
        </section>

        <section className="py-16 px-4 sm:px-8 lg:px-16 bg-blue-50">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
            <div>
              <h3 className="text-4xl font-bold">
                Your World of Care, Now In Your Pocket
              </h3>
              <p className="mt-6 text-muted-foreground">
                Download the Hovain app to get all your healthcare needs in one place. You can book appointments, consult with doctors, get prescriptions, and more.
              </p>
              <div className="mt-8 flex gap-4">
                <img src="https://placehold.co/150x50.png" alt="App Store" data-ai-hint="app store" />
                <img src="https://placehold.co/150x50.png" alt="Google Play" data-ai-hint="google play" />
              </div>
            </div>
            <div>
              <img
                src="https://placehold.co/600x400.png"
                alt="Doctor with phone"
                className="rounded-lg shadow-lg"
                data-ai-hint="doctor phone"
              />
            </div>
          </div>
        </section>

        <section className="py-16 px-4 sm:px-8 lg:px-16">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
            <div>
              <img
                src="https://placehold.co/600x400.png"
                alt="Hospital room"
                className="rounded-lg shadow-lg"
                data-ai-hint="hospital room"
              />
            </div>
            <div>
              <h3 className="text-3xl font-bold">
                Available Features In Our Partner Clinics
              </h3>
              <p className="mt-4 text-muted-foreground">
                Our partner clinics are equipped with state-of-the-art facilities and offer a wide range of services to provide you with the best possible care.
              </p>
              <div className="mt-8 flex gap-8">
                <div className="text-center">
                  <img src="https://placehold.co/100x100.png" alt="Feature 1" className="rounded-full mx-auto" data-ai-hint="medical equipment" />
                  <p className="mt-2 font-semibold">24/7 Doctors</p>
                </div>
                <div className="text-center">
                  <img src="https://placehold.co/100x100.png" alt="Feature 2" className="rounded-full mx-auto" data-ai-hint="lab test" />
                  <p className="mt-2 font-semibold">Lab Testing</p>
                </div>
                <div className="text-center">
                  <img src="https://placehold.co/100x100.png" alt="Feature 3" className="rounded-full mx-auto" data-ai-hint="medical technology" />
                  <p className="mt-2 font-semibold">Modern Technology</p>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>

      <footer className="bg-gray-900 text-gray-300 py-12 px-4 sm:px-8 lg:px-16">
        <div className="grid grid-cols-1 md:grid-cols-4 gap-8">
          <div>
            <div className="flex items-center gap-2">
              <HeartPulse className="w-8 h-8 text-pink-500" />
              <h1 className="text-2xl font-bold text-white">NovainHealth</h1>
            </div>
            <p className="mt-4 text-sm">
              Bringing quality healthcare right to your doorstep. Together, we can make healthcare more accessible, affordable, and convenient for everyone.
            </p>
          </div>
          <div>
            <h4 className="font-bold text-white">About</h4>
            <ul className="mt-4 space-y-2 text-sm">
              <li><a href="#" className="hover:text-white">Our Story</a></li>
              <li><a href="#" className="hover:text-white">Blog</a></li>
              <li><a href="#" className="hover:text-white">Careers</a></li>
            </ul>
          </div>
          <div>
            <h4 className="font-bold text-white">Download the App</h4>
            <ul className="mt-4 space-y-2 text-sm">
              <li><a href="#" className="hover:text-white">Apple App Store</a></li>
              <li><a href="#" className="hover:text-white">Google Play Store</a></li>
            </ul>
          </div>
          <div>
            <h4 className="font-bold text-white">Contact Us</h4>
            <ul className="mt-4 space-y-2 text-sm">
              <li><a href="#" className="hover:text-white">+1 234 567 8900</a></li>
              <li><a href="#" className="hover:text-white">support@novainhealth.com</a></li>
            </ul>
          </div>
        </div>
        <div className="mt-8 pt-8 border-t border-gray-700 text-center text-sm">
          <p>&copy; 2024 NovainHealth. All Rights Reserved.</p>
        </div>
      </footer>
    </div>
  );
}
